### ISSUE TITLE
Camera zoomed out and to one corner

### ISSUE THREAD

**Issue by ryan-consylman** [mebjas/html5-qrcode#36]
I am having a problem in which the canvas element does not match the video element. The video centers in and looks right. However, if I make the canvas element visible it has a very different view which is looks like the high left corner of the camera zoomed out. This seems to be the case across devices and browsers, but is worse on smaller devices. Any ideas what could cause these two elements to be out of sync and how I might re-align them?

Thank you. Btw, when the QR is within the canvas element it works great!

**Comment by OneDivZero** [comment]
maybe related to: https://github.com/mebjas/html5-qrcode/issues/26

**Comment by ryan-consylman** [comment]
> maybe related to: #26

Thanks for the tip. Looks like a fix was pushed for this and I have the most recent. Also, the issue seems slightly different.

**Comment by mebjas** [comment]
@ryan-consylman As reported by @OneDivZero there was a recent fix for related issue. Looks like this doesn't fully solve the issue. Could you share more details like OS, Browser where you are seeing this issue and also attach a screenshot and some error logs if exists ?

**Comment by ryan-consylman** [comment]
![qr_barcode_issue](https://user-images.githubusercontent.com/50520672/81067811-4832da00-8ead-11ea-8971-ff5d266cf30a.png)

I am using Chrome on Android and a Windows 10 PC, but the issue seems to be cross browser but specific to my installation. Your examples work fine for me. However, I haven't really changed anything so I was just hoping you had an idea.

**Comment by mebjas** [comment]
I see that you don't have qrbox visible, did you call `start()` with config different from following code?

```
html5QrCode.start(
  cameraId, 
  {
    fps: 10,    // Optional frame per seconds for qr code scanning
    qrbox: 250  // Optional if you want bounded box UI
  },
..
..
..
```

Can you tell the width and height of the `<div>` element where the elements are added?

**Comment by ryan-consylman** [comment]
The qrbox is visible. I just hid the shadowing around it. I suspect this is something specific to my installation and I have found a workaround by hiding the video and showing the canvas element. The camera angle is still off, but it does allow the user to see the box they need to place the barcode inside and successfully scan. I don't want to tie up more of your time. Appreciate the plugin!

**Comment by mebjas** [comment]
Ok, however if there is a bug like this still there I'd be happy to solve it.

Please let me know if your app is public or accessible so I can debug myself sometime to see whats going on.

**Comment by ryan-consylman** [comment]
I will do that when it becomes public. Thanks again!
